<a href="https://colab.research.google.com/github/edwinvincent01-maker/DA-Internship_Project/blob/main/Lead_Conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/knovist_technologies_conversion_and_sales_data.csv")
print(df)

                   Name  contact_number                    Contact_email  \
0          Anjali Singh      9931980478      anjali.singh878@hotmail.com
1            Kiran Bose      6474315136        kiran.bose601@example.com
2      Karthik Malhotra      6753707898  karthik.malhotra329@example.com
3         Anjali Sharma      9439163624      anjali.sharma85@example.com
4          Sneha Kapoor      9878269840         sneha.kapoor46@gmail.com
...                 ...             ...                              ...
27370       Rohit Reddy      6992973331       rohit.reddy220@hotmail.com
27371      Kiran Shetty      9410734029      kiran.shetty925@outlook.com
27372       Neha Shetty      9508547875         neha.shetty6@example.com
27373      Nikhil Yadav      7870690595      nikhil.yadav620@outlook.com
27374      Nikhil Reddy      8750283113        nikhil.reddy172@gmail.com

          creation_date first_call_attempt               lead_status  \
0      03-02-2026 22:31                NaN    PENDING WITH EXECUTIVE
1      03-02-2026 21:46                NaN    PENDING WITH EXECUTIVE
2      03-02-2026 21:28                NaN    PENDING WITH EXECUTIVE
3      03-02-2026 19:59                NaN    PENDING WITH EXECUTIVE
4      03-02-2026 19:19                NaN    PENDING WITH EXECUTIVE
...                 ...                ...                       ...
27370  02-06-2025 13:14   02-06-2025 14:46                    CLOSED
27371  02-06-2025 13:05                NaN                    CLOSED
27372  02-06-2025 12:39   02-06-2025 13:13                    CLOSED
27373  02-06-2025 12:35   02-06-2025 13:01  RESCHEDULED BY EXECUTIVE
27374  02-06-2025 12:35   02-06-2025 14:33  RESCHEDULED BY EXECUTIVE

               lead_stage             lead_tag assigned_to    last_call_date  \
0                Prospect                  NaN     Anshad                NaN
1                Prospect                  NaN     Anshad                NaN
2                Prospect                  NaN     Anshad                NaN
3                Prospect                  NaN     Anshad                NaN
4                Prospect                  NaN     Anshad                NaN
...                   ...                  ...         ...               ...
27370                LOST       not-interested     Riswana  02-06-2025 14:46
27371                LOST  lost-to-competition     Anshad                NaN
27372           CONVERTED                  NaN     Anshad   02-06-2025 13:13
27373  Follow Up Required                 cold     Anshad   02-06-2025 13:01
27374  Follow Up Required                 cold     Anshad   02-06-2025 14:33

      last_call_time  references            campaign_name   source_type  \
0                NaN         NaN  Data Analytics Knovista     INSTAGRAM
1                NaN         NaN  Data Analytics Knovista  FACEBOOK_ADS
2                NaN         NaN  Data Analytics Knovista     INSTAGRAM
3                NaN         NaN  Data Analytics Knovista     INSTAGRAM
4                NaN         NaN  Data Analytics Knovista     INSTAGRAM
...              ...         ...                      ...           ...
27370        2:46 PM         NaN      Business Accounting     INSTAGRAM
27371            NaN         NaN      Business Accounting     INSTAGRAM
27372        1:13 PM         NaN      Business Accounting     INSTAGRAM
27373        1:01 PM         NaN      Business Accounting     INSTAGRAM
27374        2:33 PM         NaN      Business Accounting     INSTAGRAM

        source_name
0         INSTAGRAM
1      FACEBOOK_ADS
2         INSTAGRAM
3         INSTAGRAM
4         INSTAGRAM
...             ...
27370     INSTAGRAM
27371     INSTAGRAM
27372     INSTAGRAM
27373     INSTAGRAM
27374     INSTAGRAM

[27375 rows x 15 columns]

In [ ]:
print(df.columns)
print(df.size)
print(df.shape)
print(df.dtypes)
print(df.isna().sum())

Index(['Name', 'contact_number', 'Contact_email', 'creation_date',
       'first_call_attempt', 'lead_status', 'lead_stage', 'lead_tag',
       'assigned_to', 'last_call_date', 'last_call_time', 'references',
       'campaign_name', 'source_type', 'source_name'],
      dtype='object')
410625
(27375, 15)
Name                   object
contact_number          int64
Contact_email          object
creation_date          object
first_call_attempt     object
lead_status            object
lead_stage             object
lead_tag               object
assigned_to            object
last_call_date         object
last_call_time         object
references            float64
campaign_name          object
source_type            object
source_name            object
dtype: object
Name                      0
contact_number            0
Contact_email             0
creation_date             0
first_call_attempt     6729
lead_status               0
lead_stage                0
lead_tag              11416
assigned_to               0
last_call_date         6729
last_call_time         6729
references            27375
campaign_name             0
source_type               0
source_name               0
dtype: int64

In [ ]:
print("Lead_Stage :",df.lead_stage.unique())
print("Lead_Status :",df.lead_status.unique())
print("Lead_Tag :",df.lead_tag.unique())
print("Assigned_To :",df.assigned_to.unique())
print("References :",df.references.unique())
print("Campaign :",df.campaign_name.unique())
print("Source_Name :",df.source_name.unique())
print("Source_Type :",df.source_type.unique())

Lead_Stage : ['Prospect' 'LOST' 'Follow Up Required' 'CONVERTED']
Lead_Status : ['PENDING WITH EXECUTIVE' 'CLOSED' 'NOT CONNECTED - RESCHEDULED BY SYSTEM'
 'RESCHEDULED BY EXECUTIVE' 'NOT CONNECTED - CLOSED BY SYSTEM' 'OPEN']
Lead_Tag : [nan 'not-interested' 'warm' 'cold' 'hot' 'lost-to-competition'
 'already-purchased' 'call-not-connected']
Assigned_To : ['Anshad ' ' Asiya' 'Asiya ' 'Revathy Reghu' 'Munfira' 'Dharshana'
 'Megha S' 'Amghitha' 'Sneha Rajesh' 'Shilpa Sudhakaran' 'Ardra'
 'Thaslim New' 'VIJI' 'Vijithra E' 'Shiyana nazeer' 'Riswana'
 'Anandhakrishnan' 'Devi Nandhana' 'Varsha A V' 'Hamza Anzar'
 'Ashna sathar' 'Sherin Shaji' 'Arunkumar' 'Akhil M A' 'Thaslim'
 'Ardra Shibu']
References : [nan]
Campaign : ['Data Analytics Knovista' 'PHP Knovista New' 'BA NEW 18-08-2025'
 'Digital Marketing Knovista' 'UI/UX Hiring' 'DM NO-STIPEND-23-10-2025'
 'Python Knovista New' 'BA NO STIPEND 28-10-2025'
 'Python Knovista No Stipend' 'Refurbished Campaign-PHP'
 'UI/UX no Stipend' 'Refurbished Campaign- UI/UX'
 'Refurbished Campaign- DM' 'IT DUMB' 'PHP Knovista'
 'Performance Marketing Knovista' 'Refurbished Campaign-BA'
 'Refurbished Campaign-DA' 'Refurbished Campaign-PYTHON'
 'Refurbished Campaign' 'Python Knovista'
 'Digital Marketing Learning  Knovista' 'SAP COURSE - 20-10-2025'
 'SAP Knovista' 'Business Accounting' 'Common Ads 21-08-2025']
Source_Name : ['INSTAGRAM' 'FACEBOOK_ADS' 'MOVE_LEAD'
 'DA  Hiring LEADS.xlsx/DA - KL - Hiring - july 28_Lead'
 'DA leads.xlsx/DA - KL - Hiring - july 26_Lead' 'NEODOVE_DIAL_PAD'
 'PHP LEADS.xlsx/PY_Leads_2025-11-24_2025-11-26' 'WALK_IN_LEAD'
 'dm mnew.xlsx/DM _ KL Non- Monetary Benefits'
 'UX TEST NO STIPEND AD 24-10-2025_Leads_2025-10-24_2025-11-04.csv'
 'DM AGAIN.xlsx/DM AGAIN' 'DM new.xlsx/DM - NEW - 19-08-25 – Copy_Lead'
 'acfwsacfsa.xlsx/PM - NEW - 01-10-2025_Leads_202' 'pm5-8.xlsx/pm 5-8'
 'svadsvdzvd.xlsx/DM - NEW - 19-08-25 – Copy_Lead'
 'csVXVx.xlsx/DM - NEW - 19-08-25 – Copy_Lead'
 'ABDZXGBVSDv.xlsx/DM - NEW - 19-08-25 – Copy_Lead'
 'zzdgSDGBZDg.xlsx/PM - NEW - 01-10-2025_Leads_202'
 'sap new.xlsx/SAP - KL - Hiring - 01-10-2025_'
 'Leads_PY_-_HIRING_-_STATIC_-_06-08-25.csv'
 'Leads_PY_-_We_are_looking_for_-_August_02.csv'
 'Leads_PY_-_We_are_looking_for.csv'
 '25da.xlsx/DA _ KL _ No monitory benefit _' 'weess.xlsx/Sheet1'
 'eesssss.xlsx/Sheet1' 'sss.xlsx/Sheet1' 'Common ad.xlsx/Sheet1'
 'fulll am.xlsx/Sheet1' 'hhhh.xlsx/Sheet1' 'pythonnnn.xlsx/Sheet1'
 'python new.xlsx/DA _ KL _ Hiring _ Fee included'
 'new.xlsx/BA _ KL _ July 23_Leads_2025-08' 'BA.xlsx/BA'
 'BA new.xlsx/Sheet1' 'full leads.csv']
Source_Type : ['INSTAGRAM' 'FACEBOOK_ADS' 'MOVE_LEAD' 'FILE_UPLOAD' 'NEODOVE_DIAL_PAD'
 'WALK_IN_LEAD']

References seems to have no values assigned and seems to be not required and hence the column can be removed.

In [ ]:
df=df.drop("references",axis=1)

In [ ]:
df1=df[df.iloc[:,4].isna()]
df1

,Name,contact_number,Contact_email,creation_date,first_call_attempt,lead_status,lead_stage,lead_tag,assigned_to,last_call_date,last_call_time,campaign_name,source_type,source_name
0,Anjali Singh,9931980478,anjali.singh878@hotmail.com,03-02-2026 22:31,NaN,PENDING WITH EXECUTIVE,Prospect,NaN,Anshad,NaN,NaN,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
1,Kiran Bose,6474315136,kiran.bose601@example.com,03-02-2026 21:46,NaN,PENDING WITH EXECUTIVE,Prospect,NaN,Anshad,NaN,NaN,Data Analytics Knovista,FACEBOOK_ADS,FACEBOOK_ADS
2,Karthik Malhotra,6753707898,karthik.malhotra329@example.com,03-02-2026 21:28,NaN,PENDING WITH EXECUTIVE,Prospect,NaN,Anshad,NaN,NaN,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
3,Anjali Sharma,9439163624,anjali.sharma85@example.com,03-02-2026 19:59,NaN,PENDING WITH EXECUTIVE,Prospect,NaN,Anshad,NaN,NaN,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
4,Sneha Kapoor,9878269840,sneha.kapoor46@gmail.com,03-02-2026 19:19,NaN,PENDING WITH EXECUTIVE,Prospect,NaN,Anshad,NaN,NaN,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27364,Rahul Chopra,9207193311,rahul.chopra414@yahoo.com,02-06-2025 13:36,NaN,CLOSED,LOST,lost-to-competition,Anshad,NaN,NaN,Business Accounting,INSTAGRAM,INSTAGRAM
27367,Anjali Kumar,6302208813,anjali.kumar727@gmail.com,02-06-2025 13:19,NaN,CLOSED,LOST,lost-to-competition,Anshad,NaN,NaN,Business Accounting,INSTAGRAM,INSTAGRAM
27368,Nikhil Yadav,9521868955,nikhil.yadav327@gmail.com,02-06-2025 13:16,NaN,CLOSED,LOST,lost-to-competition,Anshad,NaN,NaN,Business Accounting,INSTAGRAM,INSTAGRAM
27369,Meera Nair,6061306381,meera.nair179@yahoo.com,02-06-2025 13:14,NaN,CLOSED,LOST,lost-to-competition,Anshad,NaN,NaN,Business Accounting,INSTAGRAM,INSTAGRAM
27371,Kiran Shetty,9410734029,kiran.shetty925@outlook.com,02-06-2025 13:05,NaN,CLOSED,LOST,lost-to-competition,Anshad,NaN,NaN,Business Accounting,INSTAGRAM,INSTAGRAM

In [ ]:
print("Lead_Tag :",df.lead_tag.unique())
print("Lead_Tag :",df1.lead_tag.unique())
print("Lead_Stage :",df1.lead_stage.unique())
print("Lead_Status :",df1.lead_status.unique())

Lead_Tag : [nan 'not-interested' 'warm' 'cold' 'hot' 'lost-to-competition'
 'already-purchased' 'call-not-connected']
Lead_Tag : [nan 'lost-to-competition' 'not-interested' 'cold' 'call-not-connected'
 'already-purchased']
Lead_Stage : ['Prospect' 'LOST' 'Follow Up Required' 'CONVERTED']
Lead_Status : ['PENDING WITH EXECUTIVE' 'CLOSED' 'RESCHEDULED BY EXECUTIVE' 'OPEN']

Since the missing values in Lead Tag is not only associated with first call empty field we can fill it with those empty cells having corresponding 'Converted' with 'already Purchased.
Lead stage : Follow up required -> Lead Tag : Warm
Lead stage : prospect-> lead tag : warm
Lead stage : Lost -> lead tag : lost to competition

Lead status : Pending  with executive,open -> lead tag : call not connected
Lead status : RESCHEDULED BY EXECUTIVE -> lead tag : warm

In [ ]:
df.loc[(df['lead_stage']=='CONVERTED')&(df['lead_tag'].isna()),'lead_tag']='already-purchased'

In [ ]:
df.loc[((df['lead_stage']=='Follow Up Required')|(df['lead_stage']=='Prospect'))&(df['lead_tag'].isna()),'lead_tag']='warm'

In [ ]:
df.loc[(df['lead_stage']=='LOST')&(df['lead_tag'].isna()),'lead_tag']='lost-to-competition'

In [ ]:
print(df.isna().sum())

Name                     0
contact_number           0
Contact_email            0
creation_date            0
first_call_attempt    6729
lead_status              0
lead_stage               0
lead_tag                 0
assigned_to              0
last_call_date        6729
last_call_time        6729
campaign_name            0
source_type              0
source_name              0
dtype: int64

With mapping lead stage we were able to fill the whole empty cells under lead tag and now the only remaining empty cells is under first call attempt,last call dtae and alst call time. These fields may be missed and is only a time stamps. Hence it may not effect the ML model  for predicting the lead connvertibility and can drop those columns as well.

In [ ]:
df=df.drop(["first_call_attempt","last_call_date","last_call_time"],axis=1)
print(df)
print(df.isna().sum())
print(df.dtypes)
print(df.shape)

                   Name  contact_number                    Contact_email  \
0          Anjali Singh      9931980478      anjali.singh878@hotmail.com
1            Kiran Bose      6474315136        kiran.bose601@example.com
2      Karthik Malhotra      6753707898  karthik.malhotra329@example.com
3         Anjali Sharma      9439163624      anjali.sharma85@example.com
4          Sneha Kapoor      9878269840         sneha.kapoor46@gmail.com
...                 ...             ...                              ...
27370       Rohit Reddy      6992973331       rohit.reddy220@hotmail.com
27371      Kiran Shetty      9410734029      kiran.shetty925@outlook.com
27372       Neha Shetty      9508547875         neha.shetty6@example.com
27373      Nikhil Yadav      7870690595      nikhil.yadav620@outlook.com
27374      Nikhil Reddy      8750283113        nikhil.reddy172@gmail.com

          creation_date               lead_status          lead_stage  \
0      03-02-2026 22:31    PENDING WITH EXECUTIVE            Prospect
1      03-02-2026 21:46    PENDING WITH EXECUTIVE            Prospect
2      03-02-2026 21:28    PENDING WITH EXECUTIVE            Prospect
3      03-02-2026 19:59    PENDING WITH EXECUTIVE            Prospect
4      03-02-2026 19:19    PENDING WITH EXECUTIVE            Prospect
...                 ...                       ...                 ...
27370  02-06-2025 13:14                    CLOSED                LOST
27371  02-06-2025 13:05                    CLOSED                LOST
27372  02-06-2025 12:39                    CLOSED           CONVERTED
27373  02-06-2025 12:35  RESCHEDULED BY EXECUTIVE  Follow Up Required
27374  02-06-2025 12:35  RESCHEDULED BY EXECUTIVE  Follow Up Required

                  lead_tag assigned_to            campaign_name   source_type  \
0                     warm     Anshad   Data Analytics Knovista     INSTAGRAM
1                     warm     Anshad   Data Analytics Knovista  FACEBOOK_ADS
2                     warm     Anshad   Data Analytics Knovista     INSTAGRAM
3                     warm     Anshad   Data Analytics Knovista     INSTAGRAM
4                     warm     Anshad   Data Analytics Knovista     INSTAGRAM
...                    ...         ...                      ...           ...
27370       not-interested     Riswana      Business Accounting     INSTAGRAM
27371  lost-to-competition     Anshad       Business Accounting     INSTAGRAM
27372    already-purchased     Anshad       Business Accounting     INSTAGRAM
27373                 cold     Anshad       Business Accounting     INSTAGRAM
27374                 cold     Anshad       Business Accounting     INSTAGRAM

        source_name
0         INSTAGRAM
1      FACEBOOK_ADS
2         INSTAGRAM
3         INSTAGRAM
4         INSTAGRAM
...             ...
27370     INSTAGRAM
27371     INSTAGRAM
27372     INSTAGRAM
27373     INSTAGRAM
27374     INSTAGRAM

[27375 rows x 11 columns]
Name              0
contact_number    0
Contact_email     0
creation_date     0
lead_status       0
lead_stage        0
lead_tag          0
assigned_to       0
campaign_name     0
source_type       0
source_name       0
dtype: int64
Name              object
contact_number     int64
Contact_email     object
creation_date     object
lead_status       object
lead_stage        object
lead_tag          object
assigned_to       object
campaign_name     object
source_type       object
source_name       object
dtype: object
(27375, 11)

In [ ]:
df=df.drop_duplicates()
print(df)

                   Name  contact_number                    Contact_email  \
0          Anjali Singh      9931980478      anjali.singh878@hotmail.com
1            Kiran Bose      6474315136        kiran.bose601@example.com
2      Karthik Malhotra      6753707898  karthik.malhotra329@example.com
3         Anjali Sharma      9439163624      anjali.sharma85@example.com
4          Sneha Kapoor      9878269840         sneha.kapoor46@gmail.com
...                 ...             ...                              ...
27370       Rohit Reddy      6992973331       rohit.reddy220@hotmail.com
27371      Kiran Shetty      9410734029      kiran.shetty925@outlook.com
27372       Neha Shetty      9508547875         neha.shetty6@example.com
27373      Nikhil Yadav      7870690595      nikhil.yadav620@outlook.com
27374      Nikhil Reddy      8750283113        nikhil.reddy172@gmail.com

          creation_date               lead_status          lead_stage  \
0      03-02-2026 22:31    PENDING WITH EXECUTIVE            Prospect
1      03-02-2026 21:46    PENDING WITH EXECUTIVE            Prospect
2      03-02-2026 21:28    PENDING WITH EXECUTIVE            Prospect
3      03-02-2026 19:59    PENDING WITH EXECUTIVE            Prospect
4      03-02-2026 19:19    PENDING WITH EXECUTIVE            Prospect
...                 ...                       ...                 ...
27370  02-06-2025 13:14                    CLOSED                LOST
27371  02-06-2025 13:05                    CLOSED                LOST
27372  02-06-2025 12:39                    CLOSED           CONVERTED
27373  02-06-2025 12:35  RESCHEDULED BY EXECUTIVE  Follow Up Required
27374  02-06-2025 12:35  RESCHEDULED BY EXECUTIVE  Follow Up Required

                  lead_tag assigned_to            campaign_name   source_type  \
0                     warm     Anshad   Data Analytics Knovista     INSTAGRAM
1                     warm     Anshad   Data Analytics Knovista  FACEBOOK_ADS
2                     warm     Anshad   Data Analytics Knovista     INSTAGRAM
3                     warm     Anshad   Data Analytics Knovista     INSTAGRAM
4                     warm     Anshad   Data Analytics Knovista     INSTAGRAM
...                    ...         ...                      ...           ...
27370       not-interested     Riswana      Business Accounting     INSTAGRAM
27371  lost-to-competition     Anshad       Business Accounting     INSTAGRAM
27372    already-purchased     Anshad       Business Accounting     INSTAGRAM
27373                 cold     Anshad       Business Accounting     INSTAGRAM
27374                 cold     Anshad       Business Accounting     INSTAGRAM

        source_name
0         INSTAGRAM
1      FACEBOOK_ADS
2         INSTAGRAM
3         INSTAGRAM
4         INSTAGRAM
...             ...
27370     INSTAGRAM
27371     INSTAGRAM
27372     INSTAGRAM
27373     INSTAGRAM
27374     INSTAGRAM

[27375 rows x 11 columns]

No duplicates present. The fields Name,Contact no, Contact email, Creation date may not be useful for creating the models and we can drop those as well.

In [ ]:
df=df.drop(["Name","contact_number","Contact_email","creation_date"],axis=1)
df

,lead_status,lead_stage,lead_tag,assigned_to,campaign_name,source_type,source_name
0,PENDING WITH EXECUTIVE,Prospect,warm,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
1,PENDING WITH EXECUTIVE,Prospect,warm,Anshad,Data Analytics Knovista,FACEBOOK_ADS,FACEBOOK_ADS
2,PENDING WITH EXECUTIVE,Prospect,warm,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
3,PENDING WITH EXECUTIVE,Prospect,warm,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
4,PENDING WITH EXECUTIVE,Prospect,warm,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
...,...,...,...,...,...,...,...
27370,CLOSED,LOST,not-interested,Riswana,Business Accounting,INSTAGRAM,INSTAGRAM
27371,CLOSED,LOST,lost-to-competition,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM
27372,CLOSED,CONVERTED,already-purchased,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM
27373,RESCHEDULED BY EXECUTIVE,Follow Up Required,cold,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM
27374,RESCHEDULED BY EXECUTIVE,Follow Up Required,cold,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM

Among the data the lead stage can be considered as output so that other parameters can be changed like inouts are sources like source type, source name, campaign name with control variables like assigned to and derived inputs like lead tag and lead status. Hence we can encode using get dummy method.

In [ ]:
dummy=pd.get_dummies(df[['source_name','source_type','campaign_name','assigned_to','lead_tag','lead_status']],drop_first=True)

In [ ]:
dfn=pd.concat([df,dummy],axis=1)
dfn

,lead_status,lead_stage,lead_tag,assigned_to,campaign_name,source_type,source_name,source_name_ABDZXGBVSDv.xlsx/DM - NEW - 19-08-25 – Copy_Lead,source_name_BA new.xlsx/Sheet1,source_name_BA.xlsx/BA,...,lead_tag_cold,lead_tag_hot,lead_tag_lost-to-competition,lead_tag_not-interested,lead_tag_warm,lead_status_NOT CONNECTED - CLOSED BY SYSTEM,lead_status_NOT CONNECTED - RESCHEDULED BY SYSTEM,lead_status_OPEN,lead_status_PENDING WITH EXECUTIVE,lead_status_RESCHEDULED BY EXECUTIVE
0,PENDING WITH EXECUTIVE,Prospect,warm,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM,False,False,False,...,False,False,False,False,True,False,False,False,True,False
1,PENDING WITH EXECUTIVE,Prospect,warm,Anshad,Data Analytics Knovista,FACEBOOK_ADS,FACEBOOK_ADS,False,False,False,...,False,False,False,False,True,False,False,False,True,False
2,PENDING WITH EXECUTIVE,Prospect,warm,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM,False,False,False,...,False,False,False,False,True,False,False,False,True,False
3,PENDING WITH EXECUTIVE,Prospect,warm,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM,False,False,False,...,False,False,False,False,True,False,False,False,True,False
4,PENDING WITH EXECUTIVE,Prospect,warm,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM,False,False,False,...,False,False,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27370,CLOSED,LOST,not-interested,Riswana,Business Accounting,INSTAGRAM,INSTAGRAM,False,False,False,...,False,False,False,True,False,False,False,False,False,False
27371,CLOSED,LOST,lost-to-competition,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM,False,False,False,...,False,False,True,False,False,False,False,False,False,False
27372,CLOSED,CONVERTED,already-purchased,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27373,RESCHEDULED BY EXECUTIVE,Follow Up Required,cold,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM,False,False,False,...,True,False,False,False,False,False,False,False,False,True
27374,RESCHEDULED BY EXECUTIVE,Follow Up Required,cold,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM,False,False,False,...,True,False,False,False,False,False,False,False,False,True

In [ ]:
dfn=dfn.drop(["lead_status","lead_tag","assigned_to","campaign_name","source_type","source_name"],axis=1)
dfn

,lead_stage,source_name_ABDZXGBVSDv.xlsx/DM - NEW - 19-08-25 – Copy_Lead,source_name_BA new.xlsx/Sheet1,source_name_BA.xlsx/BA,source_name_Common ad.xlsx/Sheet1,source_name_DA Hiring LEADS.xlsx/DA - KL - Hiring - july 28_Lead,source_name_DA leads.xlsx/DA - KL - Hiring - july 26_Lead,source_name_DM AGAIN.xlsx/DM AGAIN,source_name_DM new.xlsx/DM - NEW - 19-08-25 – Copy_Lead,source_name_FACEBOOK_ADS,...,lead_tag_cold,lead_tag_hot,lead_tag_lost-to-competition,lead_tag_not-interested,lead_tag_warm,lead_status_NOT CONNECTED - CLOSED BY SYSTEM,lead_status_NOT CONNECTED - RESCHEDULED BY SYSTEM,lead_status_OPEN,lead_status_PENDING WITH EXECUTIVE,lead_status_RESCHEDULED BY EXECUTIVE
0,Prospect,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
1,Prospect,False,False,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,True,False
2,Prospect,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
3,Prospect,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
4,Prospect,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27370,LOST,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
27371,LOST,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
27372,CONVERTED,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27373,Follow Up Required,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,True
27374,Follow Up Required,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,True

In [ ]:
x=dfn.iloc[:,1:]
y=dfn.iloc[:,0]
y

0                  Prospect
1                  Prospect
2                  Prospect
3                  Prospect
4                  Prospect
                ...
27370                  LOST
27371                  LOST
27372             CONVERTED
27373    Follow Up Required
27374    Follow Up Required
Name: lead_stage, Length: 27375, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)
x_test

,source_name_ABDZXGBVSDv.xlsx/DM - NEW - 19-08-25 – Copy_Lead,source_name_BA new.xlsx/Sheet1,source_name_BA.xlsx/BA,source_name_Common ad.xlsx/Sheet1,source_name_DA Hiring LEADS.xlsx/DA - KL - Hiring - july 28_Lead,source_name_DA leads.xlsx/DA - KL - Hiring - july 26_Lead,source_name_DM AGAIN.xlsx/DM AGAIN,source_name_DM new.xlsx/DM - NEW - 19-08-25 – Copy_Lead,source_name_FACEBOOK_ADS,source_name_INSTAGRAM,...,lead_tag_cold,lead_tag_hot,lead_tag_lost-to-competition,lead_tag_not-interested,lead_tag_warm,lead_status_NOT CONNECTED - CLOSED BY SYSTEM,lead_status_NOT CONNECTED - RESCHEDULED BY SYSTEM,lead_status_OPEN,lead_status_PENDING WITH EXECUTIVE,lead_status_RESCHEDULED BY EXECUTIVE
7948,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
15609,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,True,False,True,False,False,False
25680,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
12981,False,False,False,False,False,False,False,False,False,True,...,True,False,False,False,False,False,False,False,False,True
16999,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12470,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,True,False,False,False,True,False
9760,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
6074,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,False,False,False
9873,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
8649,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[ 158    0    7    0]
 [   0  942    0   12]
 [   1    0 2340    0]
 [   0   18    0 1997]]
                    precision    recall  f1-score   support

         CONVERTED       0.99      0.96      0.98       165
Follow Up Required       0.98      0.99      0.98       954
              LOST       1.00      1.00      1.00      2341
          Prospect       0.99      0.99      0.99      2015

          accuracy                           0.99      5475
         macro avg       0.99      0.98      0.99      5475
      weighted avg       0.99      0.99      0.99      5475